name: Build .NET Framework 4.7

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore CICDTest.sln

    - name: Build solution
      run: msbuild CICDTest.sln /p:Configuration=Release /p:Platform="Any CPU"
